[mgr]
ratio = [1, 2, 3]
show_hidden = true

[opener]
play = [
	{ run = 'xdg-open "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
    { run = 'xdg-open "$@"', desc = "Open" },
]

[plugin]
# prepend_previewers = [
#   { name = "*.md", run = "glow" },
# ]
# preloaders = []
# previewers = []

[preview]
image_delay = 100
